# mail.py — HTML Email Edition
# =================================================
# send_email() now sends both a plain-text fallback and a rich HTML body.
# The HTML body is built from the plain-text `body` argument so all existing
# call-sites work without any changes.
# =================================================

from smart_logger import get_logger
logger = get_logger(__name__)

import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart

from config_mail import EmailConfig
from message_loader import Messages


# -------------------------------------------------
# HTML builder — wraps any plain-text body
# -------------------------------------------------
def _build_html(subject: str, plain_body: str) -> str:
    """
    Converts a plain-text email body into a clean HTML email.
    Preserves line breaks, highlights section separators (════ / ────),
    and wraps the whole thing in a branded card layout.
    """
    # Convert plain-text lines to HTML paragraphs
    lines = plain_body.strip().splitlines()
    html_rows = []
    for line in lines:
        stripped = line.strip()
        if not stripped:
            html_rows.append('<tr><td style="padding:4px 0;"></td></tr>')
        elif set(stripped) <= set("═=─-"):
            # Divider line
            html_rows.append(
                '<tr><td>'
                '<hr style="border:none;border-top:1px solid #E3EAF0;margin:8px 0;">'
                '</td></tr>'
            )
        else:
            # Regular content line — monospace for alignment
            escaped = (
                stripped
                .replace("&", "&amp;")
                .replace("<", "&lt;")
                .replace(">", "&gt;")
            )
            html_rows.append(
                f'<tr><td style="padding:2px 0;font-size:14px;'
                f'color:#37474F;font-family:\'Courier New\',monospace;">'
                f'{escaped}</td></tr>'
            )

    body_html = "\n".join(html_rows)

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8"/>
  <meta name="viewport" content="width=device-width,initial-scale=1.0"/>
  <title>{subject}</title>
</head>
<body style="margin:0;padding:0;background:#f0f4f8;
             font-family:'Segoe UI',Arial,sans-serif;">

  <table width="100%" cellpadding="0" cellspacing="0"
         style="background:#f0f4f8;padding:40px 0;">
    <tr><td align="center">

      <!-- Card -->
      <table width="580" cellpadding="0" cellspacing="0"
             style="background:#ffffff;border-radius:16px;
                    box-shadow:0 4px 24px rgba(0,0,0,0.08);overflow:hidden;">

        <!-- Header -->
        <tr>
          <td style="background:linear-gradient(135deg,#1A237E,#283593);
                      padding:28px 40px;text-align:center;">
            <div style="font-size:28px;margin-bottom:6px;">📊</div>
            <h1 style="margin:0;color:#ffffff;font-size:20px;font-weight:700;
                        letter-spacing:0.5px;">
              JL-CAM Notification
            </h1>
            <p style="margin:6px 0 0;color:#9FA8DA;font-size:13px;">
              {subject}
            </p>
          </td>
        </tr>

        <!-- Body -->
        <tr>
          <td style="padding:32px 40px;">
            <table width="100%" cellpadding="0" cellspacing="0"
                   style="background:#F8FAFB;border-radius:12px;
                          border:1px solid #E3EAF0;padding:20px 24px;">
              <tbody>
                {body_html}
              </tbody>
            </table>
          </td>
        </tr>

        <!-- Footer -->
        <tr>
          <td style="background:#F5F7FA;padding:18px 40px;
                      border-top:1px solid #ECEFF1;text-align:center;">
            <p style="margin:0;color:#90A4AE;font-size:12px;line-height:1.6;">
              This is an automated notification from <strong>JL-CAM System</strong>.<br>
              Please do not reply to this email.
            </p>
          </td>
        </tr>

      </table>
      <!-- /Card -->

    </td></tr>
  </table>
</body>
</html>"""


# -------------------------------------------------
# Public API
# -------------------------------------------------
def send_email(subject: str, body: str, is_html: bool = False):
    """
    Send an email with both plain-text and HTML parts.

    Args:
        subject : Email subject line.
        body    : Email body.
                  - is_html=False (default): body is plain-text; it is
                    automatically converted to HTML using _build_html().
                  - is_html=True: body is already a complete HTML document;
                    it is used as-is for the HTML part. A plain-text
                    fallback is generated by stripping tags.
    """

    logger.info(Messages.get("MAIL.SEND.001.INFO", subject=subject))

    try:
        logger.debug(
            Messages.get(
                "MAIL.SEND.002.DEBUG",
                from_email=EmailConfig.FROM_EMAIL,
                to_email=EmailConfig.TO_EMAIL,
                subject=subject,
            )
        )

        msg = MIMEMultipart("alternative")
        msg["From"]    = EmailConfig.FROM_EMAIL
        msg["To"]      = ", ".join(EmailConfig.TO_EMAIL)
        msg["Subject"] = subject

        if is_html:
            # body is already HTML — generate a simple plain-text fallback
            import re
            plain_fallback = re.sub(r"<[^>]+>", "", body).strip()
            plain_fallback = re.sub(r"\n{3,}", "\n\n", plain_fallback)
            html_body = body
        else:
            # body is plain-text — convert to HTML
            plain_fallback = body
            html_body = _build_html(subject, body)

        # Part 1 — plain text (fallback for clients that don't render HTML)
        msg.attach(MIMEText(plain_fallback, "plain"))

        # Part 2 — HTML (preferred by mail clients)
        msg.attach(MIMEText(html_body, "html"))

        logger.debug(Messages.get("MAIL.SEND.003.DEBUG"))

        logger.debug(
            Messages.get(
                "MAIL.SEND.004.DEBUG",
                smtp_server=EmailConfig.SMTP_SERVER,
                smtp_port=EmailConfig.SMTP_PORT,
            )
        )

        with smtplib.SMTP(EmailConfig.SMTP_SERVER, EmailConfig.SMTP_PORT) as server:

            logger.debug(Messages.get("MAIL.SEND.005.DEBUG"))
            server.starttls()
            logger.debug(Messages.get("MAIL.SEND.006.DEBUG"))

            logger.debug(
                Messages.get("MAIL.SEND.007.DEBUG", username=EmailConfig.USERNAME)
            )
            server.login(EmailConfig.USERNAME, EmailConfig.PASSWORD)
            logger.debug(Messages.get("MAIL.SEND.008.DEBUG"))

            logger.debug(Messages.get("MAIL.SEND.009.DEBUG"))
            server.sendmail(
                EmailConfig.FROM_EMAIL,
                EmailConfig.TO_EMAIL,
                msg.as_string(),
            )

        logger.info(Messages.get("MAIL.SEND.010.INFO", subject=subject))

    except Exception:
        logger.exception(Messages.get("MAIL.SEND.011.ERROR", subject=subject))