############################
# DATABASE CONFIG
############################
DB_NAME=jlmill
DB_USER=kaai
DB_PASSWORD=yourpassword
DB_HOST=localhost
DB_PORT=5432

############################
# MQTT CONFIG
############################
MQTT_BROKER=localhost
MQTT_PORT=1883
MQTT_DASH_TOPIC_OPEN=app/dashboard/open
MQTT_DASH_TOPIC_PUSH=app/dashboard/data
MQTT_DASHBOARD_REQUEST=vchanel/loading/request
MQTT_DASHBOARD_RESPONSE=vchanel/loading/response

############################
# IMAGE PATH
############################
IMAGE_DIR=/opt/vchanel/fastback/database/detected_frames

############################
# MAIL CONFIG
############################
MAIL_USER=kaai.support@kaaisolutions.com
MAIL_PASS=ypfZcyV9aZTU
SMTP_HOST=smtp.zoho.in
SMTP_PORT=587

############################
# CAMERA / RTSP CONFIG
############################
RTSP_FILE=config/rtsp.properties

############################
# SESSION CONFIG
############################
SESSION_TIMEOUT_HOURS=5

#send mail to user who login
SEND_USER_MAIL=false

############################
# DASHBOARD URL CONFIG
############################
IMAGE_BASE_URL=http://172.30.30.169:9000/images
