########################################################
# HEALTH MONITOR CONFIGURATION
########################################################

# -------------------------
# MQTT Configuration
# -------------------------
MQTT_HOST=localhost
MQTT_PORT=1883
MQTT_TOPIC=system/health_mqtt

# -------------------------
# Database Configuration
# -------------------------
DB_NAME=jlmill
DB_USER=kaai
DB_PASS=yourpassword
DB_HOST=localhost
DB_PORT=5432

# -------------------------
# Log File
# -------------------------
LOG_FILE=heartbeat.log
